platform :ios, '11.0'
use_frameworks!

inhibit_all_warnings!

target 'GetYourGuide' do
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'PHFDelegateChain', :git => 'https://github.com/Alterplay/PHFDelegateChain.git'
end

target 'GetYourGuideTests' do
  pod 'Swinject'
  pod 'Nimble'
  pod 'SwiftyMock'
end
